server:
  port: 8100

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

tweet:
  user:
    minFollower: 1500
  languages: es,fr,it
  hashtag:
    moreUsed:
      max: 2

twitter4j:
  debug: true
  oauth:
    consumerKey: bwMEjAH340
    consumerSecret: nYnIMrqk5QYjguY3BH4CS8yoUPb8VdJz
    accessToken: VmtrDacTJUl1M7lUyRAzL7BaqVCOVotr
    accessTokenSecret: tM6CfOKzfUbWpXY5QqGWDnN0aHDtyS
